import { Participant } from './participant'

export const PEOPLE: Participant[]= [
    {id: 1, name: 'Jane Doe', data: 'hihihihihihihiih'},
    {id: 2, name: 'Hannah Smith', data: 'hihihihihihihiih'},
    {id: 3, name: 'Lexie Phelps', data: 'hihihihihihihiih'},
    {id: 4, name: 'Safaa Garner', data: 'hihihihihihihiih'},
    {id: 5, name: 'Sonya Coulson', data: 'hihihihihihihiih'},
    {id: 6, name: 'Faris Sutherland', data: 'hihihihihihihiih'},
    {id: 7, name: 'Glen Rangel', data: 'hihihihihihihiih'},
    {id: 8, name: 'Bruce Schaefer', data: 'hihihihihihihiih'},
    {id: 9, name: 'Joely Wallis', data: 'hihihihihihihiih'},
    {id: 10, name: 'Beverly Blair', data: 'hihihihihihihiih'},
    {id: 11, name: 'Tara Woodward', data: 'hihihihihihihiih'},
    {id: 12, name: 'Nafeesa Jacobs', data: 'hihihihihihihiih'},
    {id: 13, name: 'Marina Brandt', data: 'hihihihihihihiih'},
    {id: 14, name: 'Shae Crossley', data: 'hihihihihihihiih'},
    {id: 15, name: 'Zakk Prentice', data: 'hihihihihihihiih'},
    {id: 16, name: 'Cobie Farrington', data: 'hihihihihihihiih'},
    {id: 17, name: 'Mina O\'Moore', data: 'hihihihihihihiih'},
    {id: 18, name: 'Zoey Fuentes', data: 'hihihihihihihiih'},
    {id: 19, name: 'Evie-Mae Floyd', data: 'hihihihihihihiih'},
    {id: 20, name: 'Tulisa Villa', data: 'hihihihihihihiih'},
    {id: 21, name: 'Reilly Lancaster', data: 'hihihihihihihiih'},
];
